### ISSUE TITLE
"Hacking on Ace" installation step failed

### ISSUE THREAD

**Issue by greenwich** [cucumber-attic/gherkin-editor#10]
What should be done with "Hacking on Ace" step? Because it gives following error:

./Makefile.dryice.js normal gives following: 

using targetDir ' build '
ace ---------

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot call method 'map' of undefined
    at new CommonJsProject (/usr/lib/node_modules/dryice/lib/dryice/index.js:666:27)
    at Function.createCommonJsProject (/usr/lib/node_modules/dryice/lib/dryice/index.js:974:10)
    at Object.<anonymous> (gherkin-editor/vendor/ace/Makefile.dryice.js:104:20)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

**Comment by patcon** [comment]
For what it's worth, I got this working using nvm to install node v0.4.12. I did have to update the `jasmin-node` package from `1.0.4` to `1.0.6` in `packages.json`.

Cheers!

**Comment by jdar** [comment]
patcon  ... any other hints? :) I upgraded and re-installed, but still getting the error. maybe you changed something else too?

**Comment by patcon** [comment]
upgraded? it's a big downgrade to get to node v0.4.12, just to make sure we're on the same page :)

But sorry, other than that, I think I explained everything I did to skirt around the error.

**Comment by jdar** [comment]
thanks for the reply.

If I can trouble you for one more tidbit: what version of npm are you
running?

I had intended to upgrade this project to v0.10, but now i'll be happy just
to get autocomplete working.

D

**Comment by patcon** [comment]
No sweat! Seem even when using v0.4.12 of node via `nvm`, `npm --version` still gives `1.2.0`, which is the same as my system version of `npm`. Kinda surprised me that this is the case, but apparently that's how `nvm` works
