### ISSUE TITLE
Not running on node v.0.10.31

### ISSUE THREAD

**Issue by neoecos** [cucumber-attic/gherkin-editor#13]
I have the following error

``` javascript
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.Object.defineProperty.get (module.js:388:11)
    at Object.<anonymous> (/home/sortiz/sw/src/gherkin-editor/server.js:1:70)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by CoreyMesser** [comment]
I am getting the same problem.  After reading a bit online it looks like require.paths is no longer supported and it is recommended that NODE_PATH is used. The entire server.js code needs to be rewritten or replaced.
