### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by krzysztof-jelski** [cucumber-attic/gherkin-editor#8]
I'm following instructions for running from the README.

When executing last step I get the following error:

```
~/gherkin-editor $ node server.js 

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot read property 'methods' of undefined
    at Object.<anonymous> (/home/pragmatists/.node_libraries/.npm/express/2.2.2/package/lib/http.js:15:21)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/home/pragmatists/.node_libraries/.npm/express/2.2.2/package/lib/https.js:13:18)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
```

Running latest linux mint.
node version v0.4.9
npm version 0.2.19

Tried also with Node v.0.6.10, but got error on npm link step.

**Comment by jbpros** [comment]
I can't reproduce it on Node 0.4.9. Could you try upgrading NPM first?

**Comment by krzysztof-jelski** [comment]
After upgrading npm to the latest version I get:

```
Error: npm doesn't work with node v0.4.9
```

I understand that I can get gherkin-editor working with some specific combination of npm and node. But it would be nice if it worked with whats available in ubuntu repos - either the official one or [Launchpad repo with latest versions](https://launchpad.net/~chris-lea/+archive/node.js)

**Comment by sabrams** [comment]
Looking to try this out but not familiar with node. Is there a workaround to @krzysztof-jelski 's issue?
